name: Build WalletTool

on:
  workflow_dispatch: # manuelles Ausführen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew :wallettool:shadowJar

    - name: Upload WalletTool JAR
      uses: actions/upload-artifact@v3
      with:
        name: WalletTool
        path: wallettool/build/libs/*.jar
